name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build CMake
      # You may pin to the exact commit or the version.
      # uses: ashutoshvarma/action-cmake-build@0fbeeac8b1f9c8aef99e9eae9d78529ed3b0364b
      uses: ashutoshvarma/action-cmake-build@v1
      with:
        build-dir: ${{ runner.workspace }}/build
        # will set the CC & CXX for cmake
        cc: gcc
        cxx: g++
        build-type: Release
        # Extra options pass to cmake while configuring project
        configure-options: -DCMAKE_C_FLAGS=-w32 -DPNG_INCLUDE=OFF
#         run-test: true
#         ctest-options: -R mytest
        # install the build using cmake --install
        install-build: true
        # run build using '-j [parallel]' to use multiple threads to build
        parallel: 14
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
